// Package opendkim generates DKIM keys and writes OpenDKIM config files.
package opendkim

import (
	"fmt"
	"os"
	"os/user"
	"regexp"
	"strings"

	"mailio/internal/config"
	"mailio/internal/util"
)

// KeyDir is where per-domain DKIM keys are stored.
const KeyDir = "/etc/opendkim/keys"

// GenerateKey creates (or reuses) a DKIM keypair for the domain and returns the
// public key value for the TXT record.
func GenerateKey(domain, selector string) (pubkey string, err error) {
	keyDir := fmt.Sprintf("%s/%s", KeyDir, domain)
	privkey := fmt.Sprintf("%s/%s.private", keyDir, selector)
	txtPath := fmt.Sprintf("%s/%s.txt", keyDir, selector)

	if _, err := os.Stat(privkey); os.IsNotExist(err) {
		if err := os.MkdirAll(keyDir, 0755); err != nil {
			return "", err
		}
		if err := util.Run("opendkim-genkey", "-b", "2048", "-d", domain, "-s", selector, "-D", keyDir); err != nil {
			return "", err
		}
		if err := os.Chmod(privkey, 0600); err != nil {
			return "", err
		}
		fmt.Printf("[dkim] generated key for %s\n", domain)
	} else {
		fmt.Printf("[dkim] key exists for %s, skipping\n", domain)
	}

	opendkimUser, err := user.Lookup("opendkim")
	if err != nil {
		return "", fmt.Errorf("lookup opendkim user: %w", err)
	}
	uid, gid := util.ParseInt(opendkimUser.Uid), util.ParseInt(opendkimUser.Gid)
	if err := os.Chown(privkey, uid, gid); err != nil {
		return "", fmt.Errorf("chown %s: %w", privkey, err)
	}

	return parsePubkey(txtPath)
}

func parsePubkey(txtPath string) (string, error) {
	data, err := os.ReadFile(txtPath)
	if err != nil {
		return "", err
	}
	re := regexp.MustCompile(`"([^"]+)"`)
	var sb strings.Builder
	for _, m := range re.FindAllSubmatch(data, -1) {
		sb.Write(m[1])
	}
	return sb.String(), nil
}

// WriteConf writes /etc/opendkim.conf. hostname sets AuthservID so the
// authserv-id stamped into Authentication-Results matches the value OpenDMARC
// trusts (TrustedAuthservIDs); otherwise OpenDMARC ignores OpenDKIM's results.
func WriteConf(hostname string) error {
	if err := os.MkdirAll("/etc/opendkim", 0755); err != nil {
		return err
	}
	content := fmt.Sprintf(`# generated by setup
Syslog          yes
SyslogSuccess   yes
LogWhy          yes

AuthservID      %s`, hostname) + `

KeyTable        /etc/opendkim/KeyTable
SigningTable    refile:/etc/opendkim/SigningTable
ExternalIgnoreList refile:/etc/opendkim/TrustedHosts
InternalHosts      refile:/etc/opendkim/TrustedHosts

Canonicalization    relaxed/relaxed
Mode                sv
SubDomains          no

# Do NOT sign Date (and keep to a stable header set). When mail is relayed
# through a smarthost that rewrites headers — notably consumer Gmail, which
# normalizes the Date header — a signature covering Date breaks in transit and
# DKIM fails at the recipient. Excluding Date lets the d=<domain> signature
# survive the relay so it still verifies (and aligns for DMARC). relaxed/relaxed
# body canonicalization also tolerates whitespace changes a relay may introduce.
SignHeaders         from,reply-to,subject,to,cc,message-id,mime-version,content-type,content-transfer-encoding,in-reply-to,references
AutoRestart         yes
AutoRestartRate     10/1M
Background          no

UMask           002
UserID          opendkim

Socket          inet:8891@localhost
`
	fmt.Println("[opendkim] wrote opendkim.conf")
	return os.WriteFile("/etc/opendkim.conf", []byte(content), 0644)
}

func WriteTables(domains []config.Domain) error {
	var keyLines, signLines []string
	for _, d := range domains {
		privkey := fmt.Sprintf("%s/%s/%s.private", KeyDir, d.Name, d.Selector)
		keyName := fmt.Sprintf("%s._domainkey.%s", d.Selector, d.Name)
		keyLines = append(keyLines, fmt.Sprintf("%s    %s:%s:%s", keyName, d.Name, d.Selector, privkey))
		signLines = append(signLines, fmt.Sprintf("*@%s    %s", d.Name, keyName))
	}
	if err := os.WriteFile("/etc/opendkim/KeyTable", []byte(strings.Join(keyLines, "\n")+"\n"), 0644); err != nil {
		return err
	}
	fmt.Println("[opendkim] wrote KeyTable and SigningTable")
	return os.WriteFile("/etc/opendkim/SigningTable", []byte(strings.Join(signLines, "\n")+"\n"), 0644)
}

func WriteTrustedHosts(mynetworks []string) error {
	lines := append([]string{"127.0.0.1", "::1", "localhost"}, mynetworks...)
	fmt.Println("[opendkim] wrote TrustedHosts")
	return os.WriteFile("/etc/opendkim/TrustedHosts", []byte(strings.Join(lines, "\n")+"\n"), 0644)
}
