package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/spf13/cobra"

	"mailio/internal/app"
	"mailio/internal/config"
)

func configCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "config",
		Short: "Print client configuration for the accounts",
		Long: "Everything here reads config.yml and prints it in the shape some client\n" +
			"wants. Each of these prints passwords in the clear, because that is what\n" +
			"a mail client needs — treat the output accordingly.",
	}
	cmd.AddCommand(configShowCmd(), configMuttCmd(), configMonitCmd())
	return group(cmd)
}

func configShowCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "show",
		Short:   "Print every account's SMTP credentials",
		Args:    cobra.NoArgs,
		Example: "  docker exec " + app.Name + " " + app.Name + " config show",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := loadConfig()
			if err != nil {
				return err
			}
			if asJSON, _ := cmd.Flags().GetBool("json"); asJSON {
				return renderCredsJSON(cmd.OutOrStdout(), cfg)
			}
			return renderConfig(cmd.OutOrStdout(), cfg)
		},
	}
	cmd.Flags().Bool("json", false, "print the credentials as JSON")
	return cmd
}

func configMuttCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "mutt",
		Short: "Print a mutt configuration",
		Long: "mutt takes a single account, so the first one is written out and the rest\n" +
			"follow commented out, ready to be swapped in.",
		Args:    cobra.NoArgs,
		Example: "  docker exec " + app.Name + " " + app.Name + " config mutt >> ~/.muttrc",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := loadConfig()
			if err != nil {
				return err
			}
			return renderMutt(cmd.OutOrStdout(), cfg)
		},
	}
}

func configMonitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "monit",
		Short: "Print a monit mail configuration",
		Long: "monit usually runs on the mail host and submits over loopback, so this\n" +
			"points at localhost:587 without TLS — the password never leaves the host.\n" +
			"The from address must equal the SMTP-AUTH username because of the\n" +
			"sender/login binding.",
		Args:    cobra.NoArgs,
		Example: "  docker exec " + app.Name + " " + app.Name + " config monit >> /etc/monitrc",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := loadConfig()
			if err != nil {
				return err
			}
			return renderMonit(cmd.OutOrStdout(), cfg)
		},
	}
}

// creds is one account's login, in the order a person reads it.
type creds struct {
	addr     string
	password string
}

// allCreds flattens the config into the account list every renderer here walks.
func allCreds(cfg *config.Config) []creds {
	var out []creds
	for _, d := range cfg.Domains {
		for _, acc := range d.Accounts {
			out = append(out, creds{addr: accountAddr(d.Name, acc), password: acc.Password})
		}
	}
	return out
}

// renderConfig lists every account's SMTP credentials, one block per account.
func renderConfig(w io.Writer, cfg *config.Config) error {
	accounts := allCreds(cfg)
	if len(accounts) == 0 {
		return fmt.Errorf("no accounts found in config")
	}
	for i, acc := range accounts {
		if i > 0 {
			fmt.Fprintln(w)
		}
		printCreds(w, cfg.Hostname, acc.addr, acc.password)
	}
	return nil
}

func renderCredsJSON(w io.Writer, cfg *config.Config) error {
	type entry struct {
		Address  string `json:"address"`
		Password string `json:"password"`
		SMTPURL  string `json:"smtp_url"`
	}
	out := struct {
		Hostname string  `json:"hostname"`
		Accounts []entry `json:"accounts"`
	}{Hostname: cfg.Hostname, Accounts: make([]entry, 0)}
	for _, acc := range allCreds(cfg) {
		out.Accounts = append(out.Accounts, entry{
			Address:  acc.addr,
			Password: acc.password,
			SMTPURL:  smtpURL(cfg.Hostname, acc.addr),
		})
	}
	if len(out.Accounts) == 0 {
		return fmt.Errorf("no accounts found in config")
	}
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(out)
}

func renderMutt(w io.Writer, cfg *config.Config) error {
	accounts := allCreds(cfg)
	if len(accounts) == 0 {
		return fmt.Errorf("no accounts found in config")
	}
	// The SMTP-AUTH username is the full address; its @ must be %40-encoded
	// inside smtp_url so mutt does not read it as the start of the host part.
	first := accounts[0]
	fmt.Fprintf(w, "# Generated by %s config mutt\n", app.Name)
	fmt.Fprintf(w, "# Server: %s\n\n", cfg.Hostname)
	fmt.Fprintf(w, "set from      = \"%s\"\n", first.addr)
	fmt.Fprintf(w, "set smtp_url  = \"%s\"\n", smtpURL(cfg.Hostname, first.addr))
	fmt.Fprintf(w, "set smtp_pass = \"%s\"\n", quote(first.password))

	if len(accounts) > 1 {
		fmt.Fprintf(w, "\n# Additional accounts:\n")
		for _, acc := range accounts[1:] {
			fmt.Fprintf(w, "\n# --- %s ---\n", acc.addr)
			fmt.Fprintf(w, "# set from      = \"%s\"\n", acc.addr)
			fmt.Fprintf(w, "# set smtp_url  = \"%s\"\n", smtpURL(cfg.Hostname, acc.addr))
			fmt.Fprintf(w, "# set smtp_pass = \"%s\"\n", quote(acc.password))
		}
	}
	return nil
}

func renderMonit(w io.Writer, cfg *config.Config) error {
	accounts := allCreds(cfg)
	if len(accounts) == 0 {
		return fmt.Errorf("no accounts found in config")
	}
	first := accounts[0]
	fmt.Fprintf(w, "# Generated by %s config monit\n", app.Name)
	fmt.Fprintf(w, "# Add to /etc/monitrc (or /etc/monit/monitrc) and run: monit reload\n")
	fmt.Fprintf(w, "# monit must run on the mail host (submits over localhost).\n\n")
	fmt.Fprintf(w, "set mailserver localhost port 587\n")
	fmt.Fprintf(w, "    username \"%s\" password \"%s\"\n\n", first.addr, quote(first.password))
	fmt.Fprintf(w, "set mail-format { from: Monit <%s> }\n\n", first.addr)
	fmt.Fprintf(w, "# Set your alert recipient(s), e.g.:\n")
	fmt.Fprintf(w, "# set alert you@example.com\n")

	if len(accounts) > 1 {
		fmt.Fprintf(w, "\n# Additional accounts (monit uses a single mailserver/from pair):\n")
		for _, acc := range accounts[1:] {
			fmt.Fprintf(w, "\n# --- %s ---\n", acc.addr)
			fmt.Fprintf(w, "# set mailserver localhost port 587\n")
			fmt.Fprintf(w, "#     username \"%s\" password \"%s\"\n", acc.addr, quote(acc.password))
			fmt.Fprintf(w, "# set mail-format { from: Monit <%s> }\n", acc.addr)
		}
	}
	return nil
}

// printCreds writes the email/smtp_url/password block for one account.
func printCreds(w io.Writer, hostname, addr, password string) {
	fmt.Fprintf(w, "email: %s\n", addr)
	fmt.Fprintf(w, "smtp_url: %s\n", smtpURL(hostname, addr))
	fmt.Fprintf(w, "password: %s\n", password)
}

// smtpURL builds the submission URL for an account. The username is the full
// address, so its @ is %40-encoded to keep it out of the host part.
func smtpURL(hostname, addr string) string {
	return fmt.Sprintf("smtp://%s@%s:587/", strings.ReplaceAll(addr, "@", "%40"), hostname)
}

// quote escapes a password for the double-quoted string both mutt and monit use.
func quote(password string) string {
	return strings.ReplaceAll(password, `"`, `\"`)
}
