// Package postfix writes Postfix config files and the self-signed TLS cert.
package postfix

import (
	"fmt"
	"os"
	"os/user"
	"strings"

	"mailio/internal/config"
	"mailio/internal/util"
)

// TLS certificate locations. These are referenced by main.cf and are the
// destination for both the self-signed cert and Let's Encrypt certs.
const (
	TLSCertDir  = "/etc/postfix/tls"
	TLSCertFile = TLSCertDir + "/cert.pem"
	TLSKeyFile  = TLSCertDir + "/key.pem"
)

// Relay map files, read directly as texthash maps (no postmap step needed).
//   - RelayPasswordFile holds the smarthost SMTP AUTH credentials.
//   - RelaySenderFile maps an envelope sender to its smarthost (sender-dependent
//     routing); only written when a per-domain or per-account relay is set.
const (
	RelayPasswordFile = "/etc/postfix/sasl_passwd"
	RelaySenderFile   = "/etc/postfix/sender_relay"
)

// SenderLoginFile maps each account address to the SASL login that owns it, so
// reject_sender_login_mismatch can forbid an authenticated account from sending
// as a different account. Read directly as a texthash map.
const SenderLoginFile = "/etc/postfix/sender_login"

// relayEntry is a sender-keyed relay override. Key is either a full address
// ("user@domain", per-account) or a domain ("@domain", per-domain). Postfix
// looks up the full envelope sender first and falls back to "@domain", so a
// per-account entry naturally wins over its domain's entry.
type relayEntry struct {
	Key   string
	Relay *config.Relay
}

// senderRelays collects the per-domain and per-account relay overrides. Order
// is irrelevant since Postfix looks them up by exact key.
func senderRelays(cfg *config.Config) []relayEntry {
	var out []relayEntry
	for _, d := range cfg.Domains {
		if d.Relay != nil {
			out = append(out, relayEntry{Key: "@" + d.Name, Relay: d.Relay})
		}
		for _, acc := range d.Accounts {
			if acc.Relay != nil {
				out = append(out, relayEntry{Key: acc.LocalPart + "@" + d.Name, Relay: acc.Relay})
			}
		}
	}
	return out
}

// HasRelay reports whether any relay (global, per-domain, or per-account) is
// configured, i.e. whether relay config and map files should be written.
func HasRelay(cfg *config.Config) bool {
	return cfg.Relay != nil || len(senderRelays(cfg)) > 0
}

func relayNexthop(r *config.Relay) string {
	return fmt.Sprintf("[%s]:%d", r.Host, r.EffectivePort())
}

// GenerateSelfSignedCert writes a self-signed cert/key pair if none exists.
func GenerateSelfSignedCert(hostname string) error {
	if _, err := os.Stat(TLSCertFile); err == nil {
		fmt.Println("[tls] cert already exists, skipping")
		return nil
	}
	if err := os.MkdirAll(TLSCertDir, 0755); err != nil {
		return err
	}
	fmt.Printf("[tls] generating self-signed cert for %s\n", hostname)
	return util.Run("openssl", "req", "-new", "-x509", "-days", "3650", "-nodes",
		"-subj", "/CN="+hostname,
		"-keyout", TLSKeyFile,
		"-out", TLSCertFile,
	)
}

func WriteMainCF(cfg *config.Config) error {
	domainNames := make([]string, len(cfg.Domains))
	for i, d := range cfg.Domains {
		domainNames[i] = d.Name
	}

	rootDomain := cfg.Hostname
	if idx := strings.Index(cfg.Hostname, "."); idx >= 0 {
		rootDomain = cfg.Hostname[idx+1:]
	}

	vmail, err := user.Lookup("vmail")
	if err != nil {
		return fmt.Errorf("lookup vmail user: %w", err)
	}

	// When relaying through a smarthost we carry SMTP AUTH credentials on the
	// outbound connection, so force TLS ("encrypt") to avoid leaking them over a
	// downgraded link. Without a relay, opportunistic TLS ("may") is fine.
	smtpTLSLevel := "may"
	if HasRelay(cfg) {
		smtpTLSLevel = "encrypt"
	}

	content := fmt.Sprintf(`# generated by setup
compatibility_level = 3.11
myhostname = %s
mydomain   = %s
myorigin   = $myhostname
inet_interfaces = all
inet_protocols  = ipv4

# No local delivery — virtual domains only
mydestination        =
local_recipient_maps =
local_transport      = error:local delivery disabled

virtual_mailbox_domains = %s
virtual_mailbox_base    = /var/mail
virtual_mailbox_maps    = texthash:/etc/postfix/vmailbox
virtual_uid_maps        = static:%s
virtual_gid_maps        = static:%s

# SASL
# The SMTP-AUTH username is the full address <local_part>@<domain>; an empty
# local_domain makes Cyrus derive the realm from the @domain in the username.
smtpd_sasl_auth_enable      = yes
smtpd_sasl_type             = cyrus
smtpd_sasl_path             = smtpd
smtpd_sasl_security_options = noanonymous
smtpd_sasl_local_domain     =
broken_sasl_auth_clients    = yes

# Sender/login binding: an authenticated client may only use a MAIL FROM that it
# owns (its own address). permit_mynetworks lets trusted hosts past the check.
smtpd_sender_login_maps   = texthash:%s
smtpd_sender_restrictions =
    permit_mynetworks
    reject_sender_login_mismatch

# TLS
smtp_tls_security_level  = %s
smtpd_tls_security_level = may
smtpd_tls_cert_file      = %s
smtpd_tls_key_file       = %s

# Relay policy
smtpd_relay_restrictions =
    permit_mynetworks
    permit_sasl_authenticated
    reject_unauth_destination

mynetworks =
    %s

# Milter chain. Inbound smtpd mail runs through OpenDKIM (8891, verify) then
# OpenDMARC (8893, reject on the sender domain's p=reject). non_smtpd (locally
# injected / relayed-out) mail is only signed by OpenDKIM — DMARC must never act
# on our own outbound. The submission service overrides this to OpenDKIM-only
# too (see master.cf), so authenticated outbound is signed but never evaluated.
# milter_default_action=accept means a milter being *unreachable* fails open; an
# explicit reject/tempfail from a running milter is still honored.
milter_default_action = accept
milter_protocol       = 6
smtpd_milters         = inet:localhost:8891, inet:localhost:8893
non_smtpd_milters     = inet:localhost:8891
`,
		cfg.Hostname,
		rootDomain,
		strings.Join(domainNames, " "),
		vmail.Uid,
		vmail.Gid,
		SenderLoginFile,
		smtpTLSLevel,
		TLSCertFile,
		TLSKeyFile,
		strings.Join(cfg.MyNetworks, "\n    "),
	)

	// Append the outbound relay block. relayhost + SMTP-client SASL make Postfix
	// forward outgoing mail through a smarthost instead of delivering it directly.
	// Credentials live in /etc/postfix/sasl_passwd (see WriteRelay).
	//
	// With any per-domain/per-account relay we switch to sender-dependent routing:
	// the envelope sender selects the smarthost (sender_relay) and its credentials
	// (sasl_passwd, keyed by sender), with the global relay as relayhost fallback.
	// Implicit TLS (465, wrappermode) is global-only and can't vary per sender, so
	// it's supported only when the global relay is the sole relay; otherwise 587
	// STARTTLS is required (enforced in WriteRelay).
	if HasRelay(cfg) {
		if len(senderRelays(cfg)) > 0 {
			content += fmt.Sprintf(`
# Outbound relay (smarthost, sender-dependent)
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_tls_security_options = noanonymous
smtp_sender_dependent_authentication = yes
sender_dependent_relayhost_maps = texthash:%s
smtp_sasl_password_maps = texthash:%s
`, RelaySenderFile, RelayPasswordFile)
			if cfg.Relay != nil {
				content += fmt.Sprintf("relayhost = %s\n", relayNexthop(cfg.Relay))
			}
		} else {
			r := cfg.Relay
			content += fmt.Sprintf(`
# Outbound relay (smarthost)
relayhost = %s
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = texthash:%s
smtp_sasl_security_options = noanonymous
smtp_sasl_tls_security_options = noanonymous
`, relayNexthop(r), RelayPasswordFile)
			if r.EffectivePort() == 465 {
				content += "smtp_tls_wrappermode = yes\n"
			}
		}
	}

	fmt.Println("[postfix] wrote main.cf")
	return os.WriteFile("/etc/postfix/main.cf", []byte(content), 0644)
}

func WriteMasterCF() error {
	content := `# generated by setup
# service   type  private unpriv chroot wakeup maxproc command
smtp        inet  n       -      n      -      -       smtpd
submission  inet  n       -      n      -      -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=may
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING
  -o smtpd_milters=inet:localhost:8891
pickup      unix  n       -      n      60     1       pickup
cleanup     unix  n       -      n      -      0       cleanup
qmgr        unix  n       -      n      300    1       qmgr
tlsmgr      unix  -       -      n      1000?  1       tlsmgr
rewrite     unix  -       -      n      -      -       trivial-rewrite
bounce      unix  -       -      n      -      0       bounce
defer       unix  -       -      n      -      0       bounce
trace       unix  -       -      n      -      0       bounce
verify      unix  -       -      n      -      1       verify
flush       unix  n       -      n      1000?  0       flush
proxymap    unix  -       -      n      -      -       proxymap
proxywrite  unix  -       -      n      -      1       proxymap
smtp        unix  -       -      n      -      -       smtp
relay       unix  -       -      n      -      -       smtp
showq       unix  n       -      n      -      -       showq
error       unix  -       -      n      -      -       error
retry       unix  -       -      n      -      -       error
discard     unix  -       -      n      -      -       discard
local       unix  -       n      n      -      -       local
virtual     unix  -       n      n      -      -       virtual
lmtp        unix  -       -      n      -      -       lmtp
anvil       unix  -       -      n      -      1       anvil
scache      unix  -       -      n      -      1       scache
`
	fmt.Println("[postfix] wrote master.cf")
	return os.WriteFile("/etc/postfix/master.cf", []byte(content), 0644)
}

func WriteVirtualMaps(domains []config.Domain) error {
	var mailbox []string
	for _, d := range domains {
		for _, acc := range d.Accounts {
			if acc.LocalUser == "" {
				continue
			}
			addr := fmt.Sprintf("%s@%s", acc.LocalPart, d.Name)
			mailbox = append(mailbox, fmt.Sprintf("%s    %s/", addr, acc.LocalUser))
		}
	}
	if err := os.WriteFile("/etc/postfix/vmailbox", []byte(strings.Join(mailbox, "\n")+"\n"), 0644); err != nil {
		return err
	}
	fmt.Println("[postfix] wrote vmailbox")
	return nil
}

// WriteSenderLogin writes the sender-login ownership map: each account address
// is owned by the SASL login of the same name (the full address). Postfix uses
// it with reject_sender_login_mismatch to keep one account from sending as
// another.
func WriteSenderLogin(domains []config.Domain) error {
	var lines []string
	for _, d := range domains {
		for _, acc := range d.Accounts {
			addr := acc.LocalPart + "@" + d.Name
			lines = append(lines, fmt.Sprintf("%s    %s", addr, addr))
		}
	}
	if err := os.WriteFile(SenderLoginFile, []byte(strings.Join(lines, "\n")+"\n"), 0644); err != nil {
		return err
	}
	fmt.Println("[postfix] wrote sender_login")
	return nil
}

func validateRelay(r *config.Relay) error {
	if r.Host == "" || r.Username == "" || r.Password == "" {
		return fmt.Errorf("requires host, username and password")
	}
	return nil
}

// writeSecret writes content to path owned root:postfix mode 0640, so the
// unprivileged smtp(8) client can read it while keeping the password off
// world-readable storage. It writes 0600 first so the file is never briefly
// group-readable before the chown narrows ownership.
func writeSecret(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return err
	}
	if err := util.Run("chown", "root:postfix", path); err != nil {
		return err
	}
	return os.Chmod(path, 0640)
}

// WriteRelay writes the relay map files from the config: RelayPasswordFile
// always, and RelaySenderFile when any per-domain/per-account relay is set.
// Caller should only invoke this when HasRelay(cfg) is true.
func WriteRelay(cfg *config.Config) error {
	entries := senderRelays(cfg)
	senderDependent := len(entries) > 0

	var passwd, sender []string

	// Per-domain / per-account overrides: keyed by envelope sender.
	for _, e := range entries {
		r := e.Relay
		if err := validateRelay(r); err != nil {
			return fmt.Errorf("relay for %s: %w", e.Key, err)
		}
		if r.EffectivePort() == 465 {
			return fmt.Errorf("relay for %s: port 465 (implicit TLS) is not supported "+
				"with per-domain/per-account relays; use 587 (STARTTLS)", e.Key)
		}
		sender = append(sender, fmt.Sprintf("%s    %s", e.Key, relayNexthop(r)))
		passwd = append(passwd, fmt.Sprintf("%s    %s:%s", e.Key, r.Username, r.Password))
	}

	// Global relay: the relayhost fallback, keyed by nexthop destination.
	if cfg.Relay != nil {
		r := cfg.Relay
		if err := validateRelay(r); err != nil {
			return fmt.Errorf("global relay: %w", err)
		}
		if senderDependent && r.EffectivePort() == 465 {
			return fmt.Errorf("global relay: port 465 (implicit TLS) is not supported " +
				"alongside per-domain/per-account relays; use 587 (STARTTLS)")
		}
		passwd = append(passwd, fmt.Sprintf("%s    %s:%s", relayNexthop(r), r.Username, r.Password))
	}

	if err := writeSecret(RelayPasswordFile, strings.Join(passwd, "\n")+"\n"); err != nil {
		return err
	}
	fmt.Println("[postfix] wrote relay sasl_passwd")

	if senderDependent {
		// sender_relay holds no secrets, so 0644 is fine.
		if err := os.WriteFile(RelaySenderFile, []byte(strings.Join(sender, "\n")+"\n"), 0644); err != nil {
			return err
		}
		fmt.Println("[postfix] wrote relay sender_relay")
	}
	return nil
}

func SetupMaildirs(domains []config.Domain) error {
	vmail, err := user.Lookup("vmail")
	if err != nil {
		return fmt.Errorf("lookup vmail user: %w", err)
	}
	uid, gid := util.ParseInt(vmail.Uid), util.ParseInt(vmail.Gid)

	seen := map[string]bool{}
	for _, d := range domains {
		for _, acc := range d.Accounts {
			if acc.LocalUser == "" || seen[acc.LocalUser] {
				continue
			}
			seen[acc.LocalUser] = true
			base := fmt.Sprintf("/var/mail/%s", acc.LocalUser)
			if fi, err := os.Stat(base); err == nil && !fi.IsDir() {
				if err := os.Remove(base); err != nil {
					return fmt.Errorf("remove stale mbox %s: %w", base, err)
				}
			}
			for _, sub := range []string{"cur", "new", "tmp"} {
				dir := fmt.Sprintf("/var/mail/%s/%s", acc.LocalUser, sub)
				if err := os.MkdirAll(dir, 0700); err != nil {
					return fmt.Errorf("mkdir %s: %w", dir, err)
				}
				if err := os.Chown(dir, uid, gid); err != nil {
					return fmt.Errorf("chown %s: %w", dir, err)
				}
			}
			if err := os.Chown(base, uid, gid); err != nil {
				return fmt.Errorf("chown %s: %w", base, err)
			}
			fmt.Printf("[postfix] maildir ready: %s\n", base)
		}
	}
	return nil
}
