// Package opendmarc writes the OpenDMARC milter config. OpenDMARC runs after
// OpenDKIM in the milter chain and rejects inbound mail that fails DMARC when
// the sending domain publishes a "p=reject" policy.
package opendmarc

import (
	"fmt"
	"os"
)

// RunDir is OpenDMARC's working directory (BaseDirectory). It must exist and be
// owned by the opendmarc user before the daemon starts; setup creates it.
const RunDir = "/run/opendmarc"

// WriteConf writes /etc/opendmarc.conf. hostname is used as the authserv-id so
// it matches the value OpenDKIM stamps into Authentication-Results; OpenDMARC
// only trusts (and reuses) DKIM results carrying an authserv-id it recognizes.
func WriteConf(hostname string) error {
	// SPFIgnoreResults + SPFSelfValidate: we run no separate SPF policy milter,
	// so don't trust any Received-SPF/Authentication-Results SPF header on the
	// wire (could be forged) — have OpenDMARC perform its own SPF check via
	// libspf2 instead. DMARC then passes on either aligned SPF or aligned DKIM.
	//
	// IgnoreAuthenticatedClients keeps DMARC off our own authenticated
	// submission (outbound) mail; RejectFailures makes a DMARC failure an SMTP
	// reject (only when the sender's domain policy is p=reject — p=quarantine
	// and p=none are annotated, not rejected). RequiredHeaders rejects malformed
	// RFC5322 headers (e.g. no usable From: domain) outright.
	content := fmt.Sprintf(`# generated by setup
AuthservID                 %s
TrustedAuthservIDs         %s
Socket                     inet:8893@localhost
UserID                     opendmarc
BaseDirectory              %s
UMask                      007
RejectFailures             true
IgnoreAuthenticatedClients true
RequiredHeaders            true
SPFIgnoreResults           true
SPFSelfValidate            true
SoftwareHeader             true
Syslog                     yes
`, hostname, hostname, RunDir)

	fmt.Println("[opendmarc] wrote opendmarc.conf")
	return os.WriteFile("/etc/opendmarc.conf", []byte(content), 0644)
}
